version: '3.6'
services:
  maxdb:
    image: maximo-liberty/db2:7.6.1.1
    hostname: "${ENV_MAXDB_SERVICE_HOST}"
    environment:
      - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
      - "MAXDB_SERVICE_PORT=${ENV_MAXDB_SERVICE_PORT}"
    networks:
      - backend
    ports:
      - "${ENV_MAXDB_SERVICE_PORT}:${ENV_MAXDB_SERVICE_PORT}"
    volumes:
      - type: volume
        source: maxdb76
        target: /home/ctginst1/ctginst1
#      - type: bind
#        source: ./backup
#        target: /backup
    ulimits:
      nproc: 8192
      nofile: 65535
      fsize: -1
    healthcheck:
      test: ["CMD", "/work/db2/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
#  maximo:
#    image: maximo-liberty/maximo:7.6.1.1
#    environment:
#      - MXINTADM_PASSWORD=changeit
#      - MAXADMIN_PASSWORD=changeit
#      - MAXREG_PASSWORD=changeit
#      - "MAXDB_SERVICE_PORT=${ENV_MAXDB_SERVICE_PORT}"
#      - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
#      - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
#      - BASE_LANG=en
#      - ADD_LANGS=de,fr,ja
#      - ADMIN_EMAIL_ADDRESS=root@localhost
#      - SMTP_SERVER_HOST_NAME=localhost
#      - SKIN=iot18
#      - UPDATE_APPS_ON_REBOOT=yes
#      - KEEP_RUNNING=yes
#      - ENABLE_DEMO_DATA=no
#    depends_on:
#      - maxdb
#    networks:
#      - backend
#    volumes:
#      - maximo:/maximo

  maximo-ui:
    image: maximo-liberty/maximo-ui:7.6.1.1
    environment:
      - "MAXDB_SERVICE_PORT=${ENV_MAXDB_SERVICE_PORT}"
      - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
      - GEN_MAXIMO_PROPERTIES=yes
      - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
      - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
      - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
      - LICENSE=accept
      - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
      - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
      - WLP_LOGGING_CONSOLE_LOGLEVEL=info
    depends_on:
      - maxdb
#      - maximo
      - jmsserver
    networks:
      frontend:
        aliases:
          - maximo-ui
      backend:
    volumes:
      - maximo:/maximo

  maximo-cron:
    image: maximo-liberty/maximo-cron:7.6.1.1
    environment:
      - "MAXDB_SERVICE_PORT=${ENV_MAXDB_SERVICE_PORT}"
      - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
      - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
      - GEN_MAXIMO_PROPERTIES=yes
      - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
      - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
      - LICENSE=accept
      - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
      - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
    depends_on:
      - maxdb
#      - maximo
      - jmsserver
    networks:
      frontend:
      backend:
    volumes:
      - maximo:/maximo

  # maximo-api:
  #   image: maximo-liberty/maximo-api:7.6.1.1
  #   environment:
  #     - "MAXDB_SERVICE_PORT=${ENV_MAXDB_SERVICE_PORT}"
  #     - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
  #     - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
  #     - GEN_MAXIMO_PROPERTIES=yes
  #     - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
  #     - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
  #     - LICENSE=accept
  #     - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
  #     - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
  #   depends_on:
  #     - maxdb
  #     - maximo
  #     - jmsserver
  #   networks:
  #     frontend:
  #       aliases:
  #         - maximo-api
  #     backend:
  #   volumes:
  #     - maximo:/maximo

  # maximo-report:
  #   image: maximo-liberty/maximo-report:7.6.1.1
  #   environment:
  #     - "MAXDB_SERVICE_PORT=${ENV_MAXDB_SERVICE_PORT}"
  #     - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
  #     - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
  #     - GEN_MAXIMO_PROPERTIES=yes
  #     - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
  #     - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
  #     - LICENSE=accept
  #     - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
  #     - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
  #   depends_on:
  #     - maxdb
  #     - maximo
  #     - jmsserver
  #   networks:
  #     frontend:
  #       aliases:
  #         - maximo-report
  #     backend:
  #   volumes:
  #     - maximo:/maximo

  # maximo-mea:
  #   image: maximo-liberty/maximo-mea:7.6.1.1
  #   environment:
  #     - "MAXDB_SERVICE_PORT=${ENV_MAXDB_SERVICE_PORT}"
  #     - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
  #     - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
  #     - GEN_MAXIMO_PROPERTIES=yes
  #     - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
  #     - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
  #     - LICENSE=accept
  #     - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
  #     - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
  #   depends_on:
  #     - maxdb
  #     - maximo
  #     - jmsserver
  #   networks:
  #    frontend:
  #      aliases:
  #        - maximo-mea
  #     backend:
  #   volumes:
  #     - maximo:/maximo

  # maximo-jmsconsumer:
  #   image: maximo-liberty/maximo-jmsconsumer:7.6.1.1
  #   environment:
  #     - "MAXDB_SERVICE_PORT=${ENV_MAXDB_SERVICE_PORT}"
  #     - "MAXDB_SERVICE_HOST=${ENV_MAXDB_SERVICE_HOST}"
  #     - "DB_MAXIMO_PASSWORD=${ENV_DB_MAXIMO_PASSWORD}"
  #     - GEN_MAXIMO_PROPERTIES=yes
  #     - "ADMIN_USER_NAME=${ENV_ADMIN_USER_NAME}"
  #     - "ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}"
  #     - LICENSE=accept
  #     - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
  #     - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
  #   depends_on:
  #     - maxdb
  #     - maximo
  #     - jmsserver
  #   networks:
  #     frontend:
  #       aliases:
  #         - maximo-jmsconsumer
  #     backend:
  #   volumes:
  #     - maximo:/maximo

  jmsserver:
    image: maximo-liberty/jmsserver:19.0.0.6-webProfile8
    environment:
      - LICENSE=accept
      - "MAXIMO_JMS_SERVICE_HOST=${ENV_MAXIMO_JMS_SERVICE_HOST}"
      - "MAXIMO_JMS_SERVICE_PORT=${ENV_MAXIMO_JMS_SERVICE_PORT}"
      - "MAXIMO_JMS_SERVICE_SSL_PORT=${ENV_MAXIMO_JMS_SERVICE_SSL_PORT}"
    hostname: "${ENV_MAXIMO_JMS_SERVICE_HOST}"
    ports:
      - "${ENV_MAXIMO_JMS_SERVICE_PORT}:${ENV_MAXIMO_JMS_SERVICE_PORT}"
      - "${ENV_MAXIMO_JMS_SERVICE_SSL_PORT}:${ENV_MAXIMO_JMS_SERVICE_SSL_PORT}"
    networks:
      - frontend

  frontend-proxy:
    image: maximo-liberty/frontend-proxy:1.8
    ports:
      - 80:80
    depends_on:
      - maximo-ui
    networks:
      - frontend

networks:
  frontend:
  backend:
volumes:
  maxdb76:
  # Shared directory for liberty deployment files
  maximo:
